<?php

declare(strict_types=1);

return [
    'name' => 'Chat',
    'SEED_CHAT_CATEGORIES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNEL_PARTICIPANTS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNEL_TOPIC_FILES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNEL_TOPIC_MESSAGE_FILES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNEL_TOPIC_MESSAGES_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNEL_TOPICS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNEL_USERS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_CHANNELS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CATEGORY_PARTICIPANTS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_CONFIGS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_GROUP_PERMISSIONS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_PARTICIPANTS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_PERMISSION_GROUP_USERS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_PERMISSION_GROUPS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_PERMISSIONS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_USER_PERMISSIONS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHAT_USERS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHATS_COUNT' => env('SEEDER_DEFAULT', 3),
    'SEED_CHATS_IN_PRODUCTION' => env('SEED_CHATS_IN_PRODUCTION', false),
];
