<?php

return [
    'name' => 'Chat',
    'SEED_CHAT_CATEGORIES_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNEL_PARTICIPANTS_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNEL_TOPIC_FILES_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNEL_TOPIC_MESSAGE_FILES_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNEL_TOPIC_MESSAGES_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNEL_TOPICS_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNEL_USERS_COUNT' => 3,
    'SEED_CHAT_CATEGORY_CHANNELS_COUNT' => 3,
    'SEED_CHAT_CATEGORY_PARTICIPANTS_COUNT' => 3,
    'SEED_CHAT_CONFIGS_COUNT' => 3,
    'SEED_CHAT_GROUP_PERMISSIONS_COUNT' => 3,
    'SEED_CHAT_PARTICIPANTS_COUNT' => 3,
    'SEED_CHAT_PERMISSION_GROUP_USERS_COUNT' => 3,
    'SEED_CHAT_PERMISSION_GROUPS_COUNT' => 3,
    'SEED_CHAT_PERMISSIONS_COUNT' => 3,
    'SEED_CHAT_USER_PERMISSIONS_COUNT' => 3,
    'SEED_CHAT_USERS_COUNT' => 3,
    'SEED_CHATS_COUNT' => 3,
];
